name: Variables

on:
  workflow_dispatch:

jobs:
   deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Next Release Number
        id: next-release-details
        run: |
          IFS='.' read -ra version_parts <<< "${{ vars.RELEASE_VERSION }}"
          major="${version_parts[0]}"
          minor="${version_parts[1]}"
          patch="$((version_parts[2] + 1))"
          new_version="$major.$minor.$patch"          
          echo "NEW_RELESE_VERSION=$new_version" >> "$GITHUB_OUTPUT"

      - run: steps.next-release-details.NEW_RELESE_VERSION
