name: Variables

on:
  workflow_dispatch:

jobs:
   deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Verify Release Number
        id: semver
        uses: matt-usurp/validate-semver@v1.1.1
        with:
          version: '1.0.0'

      - run: |
          new_patch=$((${{ steps.semver.outputs.patch }}  + 1))
          echo "v${{ steps.semver.outputs.version }}"
          echo "${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}.${{ new_patch }}"
