name: Variables

on:
  workflow_dispatch:

jobs:
   deploy:
    runs-on: ubuntu-latest

    steps:
      - run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.AUTH_TOKEN2 }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/NAME \
            -d '{"name":"RELEASE_VERSION","value":"1.0.5"}'