name: Variables

on:
  workflow_dispatch:

jobs:
   deploy:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo ${{ github.repository }}
          gh variable list --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN2 }}