name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: "Build Changelog"
          id: build_changelog
          uses: mikepenz/release-changelog-builder-action@v4.0.1

        - name: Create Release
          uses: mikepenz/action-gh-release@v0.2.0-a03
          with:
            body: ${{ steps.build_changelog.outputs.changelog }}

