name: Release 🚀

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the current branch is 'develop'
        if: github.ref != 'refs/heads/feature/ps-0000-new-release'
        run: |
          echo "The current branch is not 'develop'. Exiting workflow."
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

