name: Release 🚀

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the current branch is 'develop'
        if: github.ref != 'refs/heads/feature/ps-0000-new-release'
        run: |
          echo "The current branch is not 'develop'. Exiting workflow."
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate release number
        id: release-number
        run: |
          echo "RELEASE_VERSION=v${{ vars.RELEASE_VERSION }}" >> "$GITHUB_OUTPUT"
      
      - name: Validate release numner
        id: semver
        uses: matt-usurp/validate-semver@v1.1.1
        with:
            version: ${{ steps.release-number.outputs.RELEASE_VERSION }}

      - name: Checkout source code
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
        

