name: Release 🚀

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the current branch is 'develop'
        if: github.ref != 'refs/heads/feature/ps-0000-new-release'
        run: |
          echo "The current branch is not 'develop'. Exiting workflow."
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate Release Information
        id: release
        run: |
          echo "TAG=v${{ vars.RELEASE_VERSION }}" >> "$GITHUB_OUTPUT"
          echo "BRANCH=release/v${{ vars.RELEASE_VERSION }}" >> "$GITHUB_OUTPUT"
      
      - name: Verify Release Number
        id: semver
        uses: matt-usurp/validate-semver@v1.1.1
        with:
            version: ${{ steps.release.outputs.TAG }}

      - name: Checkout Source Code
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}
        
      - name: Set Up Mandatory Git Configuration
        run: |
          git config user.name "Release manager"
          git config user.email noreply@github.com

      - name: Create Annotated Tag
        run: |
          git tag -a ${{ steps.release.outputs.TAG }} -m "Release ${{ steps.release.outputs.TAG }}"

      - name: Push Annotated Tag
        run: git push

